routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ShareController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');

    Route::resource('files', FileController::class)->except(['edit', 'create', 'update']);

    Route::post('share', [ShareController::class, 'store'])->name('share.store');

    Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
});

Route::get('share/{token}', [ShareController::class, 'get'])->name('share.get');

app/Models/File.php
<?php

namespace App\Models;

use App\Scopes\AuthenticatedUserScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @OA\Schema()
 *     type="object",
 *     title="File",
 *     description="A file model"
 */
class File extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'path',
        'name',
        'comment',
        'delete_at',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function shareTokens(): HasMany
    {
        return $this->hasMany(ShareToken::class)->latest();
    }

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::addGlobalScope(new AuthenticatedUserScope());
    }
}

app/Http/Controllers/API/v1/FileController.php
<?php

namespace App\Http\Controllers\API\v1;

use App\Http\Requests\StoreFileRequest;
use App\Models\File;
use App\Repositories\Contracts\FileRepository;
use App\Services\FileService;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{
    private FileService $service;
    private FileRepository $repository;

    public function __construct(FileService $service, FileRepository $repository)
    {
        $this->service = $service;
        $this->repository = $repository;
    }

    /**
     * @OA\get(path="/api/v1/files",
     *   tags={"Files"},
     *   summary="Show user files",
     *   @OA\Response(
     *     response="200",
     *     description="OK"
     *   )
     * )
     */
    public function index(): JsonResponse
    {
        $files = $this->repository->latest();
        $filesCount = count($files);

        return $this->sendResponse(compact('files', 'filesCount'));
    }

    /**
     * @OA\Post(path="/api/v1/files",
     *   tags={"Files"},
     *   summary="Store file",
     *   operationId="getFileById",
     *   @OA\Parameter(name="file",
     *     in="query",
     *     required=true,
     *     @OA\Schema(type="file")
     *   ),
     *   @OA\Parameter(name="comment",
     *     in="query",
     *     required=false,
     *     @OA\Schema(type="string")
     *   ),
     *   @OA\Parameter(name="delete_at",
     *     in="query",
     *     required=false,
     *     @OA\Schema(type="string", format="date")
     *   ),
     *   @OA\Response(
     *     response="200",
     *     description="OK",
     *   @OA\JsonContent(
     *              type="object",
     *              @OA\Property(
     *                  property="success",
     *                  type="boolean"
     *              ),
     *              @OA\Property(
     *                  property="data",
     *                  type="object"
     *              ),
     *              @OA\Property(
     *                  property="message",
     *                  type="string"
     *              )
     *          )
     *   )
     *   )
     * )
     */
    public function store(StoreFileRequest $request): JsonResponse
    {
        $userId = Auth::id();

        $file = $this->service->store($request->validated(), $userId);

        if (is_null($file)) {
            return $this->sendError(__('Upload failed.'));
        }

        return $this->sendResponse($file, __('Uploaded.'));
    }

    /**
     * @OA\Get(path="/api/v1/files/{id}",
     *   tags={"Files"},
     *   summary="Show file by id",
     *   operationId="getFileById",
     *   @OA\Parameter(name="id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(type="string")
     *   ),
     *   @OA\Response(
     *     response="200",
     *     description="OK",
     *   @OA\JsonContent(
     *              type="object",
     *              @OA\Property(
     *                  property="success",
     *                  type="boolean"
     *              ),
     *              @OA\Property(
     *                  property="data",
     *                  type="object"
     *              ),
     *              @OA\Property(
     *                  property="message",
     *                  type="string"
     *              )
     *          )
     *   )
     *   )
     * )
     */
    public function show(int $id): JsonResponse
    {
        $file = $this->service->show($id);

        return $this->sendResponse($file);
    }

    /**
     * @OA\Delete (path="/api/v1/files/{id}",
     *   tags={"Files"},
     *   summary="Delete file by id",
     *   operationId="deleteFileById",
     *   @OA\Parameter(name="id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(type="integer")
     *   ),
     *   @OA\Response(
     *     response="200",
     *     description="OK",
     *   @OA\JsonContent(
     *              type="object",
     *              @OA\Property(
     *                  property="success",
     *                  type="boolean"
     *              ),
     *              @OA\Property(
     *                  property="data",
     *                  type="object"
     *              ),
     *              @OA\Property(
     *                  property="message",
     *                  type="string"
     *              )
     *          )
     *    )
     *   ),
     *   security={
     *     "api_key":{}
     *   }
     * )
     */
    public function destroy(int $id): JsonResponse
    {
        $this->repository->delete($id);

        return $this->sendResponse(null, __('Deleted successfully'));
    }

    /**
     * @param $id
     * @return mixed
     *
     * @OA\Get (path="/api/v1/files/{id}/download",
     *   tags={"Files"},
     *   summary="Download file by id",
     *   operationId="downloadFileById",
     *   @OA\Parameter(name="id",
     *     in="path",
     *     required=true,
     *     @OA\Schema(type="integer")
     *   ),
     *   @OA\Response(
     *     response="200",
     *     description="OK",
     *   )
     *   )
     * )
     */
    public function download(int $id)
    {
        $file = $this->repository->find($id);

        return Storage::download($file['path']);
    }
}

app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreFileRequest;
use App\Services\FileService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class FileController extends Controller
{
    private FileService $service;

    public function __construct(FileService $service)
    {
        $this->service = $service;
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $result = $this->service->index();

        return view('pages.files.index')->with($result);
    }

    public function store(StoreFileRequest $request): RedirectResponse
    {
        $userId = Auth::id();

        $file = $this->service->store($request->validated(), $userId);

        if (is_null($file)) {
            return redirect()->back()->withErrors([
                'file' => __('Failed to upload file.')
            ]);
        }

        return redirect()->route('files.show', [
            'file' => $file['id']
        ]);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(int $id)
    {
        $file = $this->service->show($id);

        return view('pages.files.show')->with(compact('file'));
    }

    public function destroy(int $id): RedirectResponse
    {
        $this->service->destroy($id);

        return redirect()->route('files.index')->with([
            'status' => __('Deleted successfully.')
        ]);
    }
}

resources/views/pages/files/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('List') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div>
                        Files count {{$filesCount}}
                    </div>

                    @empty($files)
                        <div>No files uploaded.</div>
                    @else
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">{{__('ID')}}</th>
                                    <th scope="col">{{__('Name')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($files as $file)
                                <tr>
                                    <td scope="row">
                                        <a href="{{route('files.show', ['file' => $file['id']])}}">
                                            {{$file['id']}}
                                        </a>
                                    </td>
                                    <td>{{$file['name']}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endempty
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/files/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('File') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @isset($file['delete_at'])
                        <div>Will be deleted: {{$file['delete_at']}}</div>
                    @endisset

                    @isset($file['comment'])
                        <div>Comment: {{$file['comment']}}</div>
                    @endisset

                    <form class="mt-2" action="{{route('files.destroy', ['file' => $file['id']])}}" method="post">
                        @method('DELETE')
                        @csrf

                        <button class="btn btn-danger" type="submit">{{__('Delete file')}}</button>
                    </form>

                    <form class="mt-2 form-inline" action="{{route('share.store')}}" method="post">
                        @csrf
                        <input type="hidden" name="file_id" value="{{$file['id']}}">
                        <div class="form-group">
                            <label for="type">{{__('Token type:')}} </label>
                            <select name="type" class="form-control ml-3" id="type">
                                <option value="0" selected>{{__('Unlimited')}}</option>
                                <option value="1">{{__('Limited')}}</option>
                            </select>
                        </div>

                        <button class="btn btn-success ml-3" type="submit">{{__('Generate token')}}</button>
                    </form>

                    <table class="table mt-3">
                        <thead>
                            <tr>
                                <th scope="col">{{__('Share link')}}</th>
                                <th scope="col">{{__('Active')}}</th>
                                <th scope="col">{{__('Type')}}</th>
                                <th scope="col">{{__('Viewed')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($file['share_tokens'] ?? [] as $token)
                            <tr>
                                <td scope="row">
                                    <a href="{{route('share.get', ['token' => $token['token']])}}" target="_blank">
                                        {{$token['token']}}
                                    </a>
                                </td>
                                <td>{{$token['active'] ? '+' : '-'}}</td>
                                <td>
                                    @if($token['type'] === 0)
                                        Unlimited
                                    @elseif($token['type'] === 1)
                                        Limited
                                    @endif
                                </td>
                                <td>{{$token['viewed']}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection